name: Mirror & Test

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      MIRROR_ONE: ${{ secrets.MIRROR_ONE }}
    steps:
    - name: mirror repo
      run: git clone https://github.com/Khuirul-Huda/my-writing.git
      run: cd my-writing 
      run: ls && git push $MIRROR_ONE --all
      run: |
       cd ..
       rm -rf my-writing
#todo #checks
