name: Mirror & Test

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      MIRROR_ONE: ${{ secrets.MIRROR_ONE }}
    steps:
    - name: Clone Repository
      run: git clone https://github.com/Khuirul-Huda/my-writing.git
    - name: Prepare to push
      run: cd my-writing
    - name: Push to Mirror
      run: git push "$MIRROR_ONE" --all 2> .log
    - name: Cleanup
      run: |
       cd ..
       rm -rf my-writing
#todo #checks
